[
    {
        "image_path": "/home/yuyangxin/data/dataset/MSCOCO/train2017/000000000094.jpg",
        "error_info": "Traceback (most recent call last):\n  File \"/home/yuyangxin/data/experiment/main.py\", line 142, in <module>\n    future.result()  # 获取结果\n    ^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 114, in process_images\n    result = app.run(image_path, detail_info)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 90, in run\n    modify_mask = utils.mask_change(src_mask, start_point, modify_detail.end_point, \"copying\")\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/processor/utils.py\", line 127, in mask_change\n    raise ValueError(\"目标区域超出编辑范围\")\nValueError: 目标区域超出编辑范围\n"
    },
    {
        "image_path": "/home/yuyangxin/data/dataset/MSCOCO/train2017/000000000049.jpg",
        "error_info": "Traceback (most recent call last):\n  File \"/home/yuyangxin/data/experiment/main.py\", line 142, in <module>\n    future.result()  # 获取结果\n    ^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 114, in process_images\n    result = app.run(image_path, detail_info)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 90, in run\n    modify_mask = utils.mask_change(src_mask, start_point, modify_detail.end_point, \"copying\")\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/processor/utils.py\", line 127, in mask_change\n    raise ValueError(\"目标区域超出编辑范围\")\nValueError: 目标区域超出编辑范围\n"
    },
    {
        "image_path": "/home/yuyangxin/data/dataset/MSCOCO/train2017/000000000064.jpg",
        "error_info": "Traceback (most recent call last):\n  File \"/home/yuyangxin/data/experiment/main.py\", line 142, in <module>\n    future.result()  # 获取结果\n    ^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 114, in process_images\n    result = app.run(image_path, detail_info)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 90, in run\n    modify_mask = utils.mask_change(src_mask, start_point, modify_detail.end_point, \"copying\")\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/processor/utils.py\", line 127, in mask_change\n    raise ValueError(\"目标区域超出编辑范围\")\nValueError: 目标区域超出编辑范围\n"
    },
    {
        "image_path": "/home/yuyangxin/data/dataset/MSCOCO/train2017/000000000061.jpg",
        "error_info": "Traceback (most recent call last):\n  File \"/home/yuyangxin/data/experiment/main.py\", line 142, in <module>\n    future.result()  # 获取结果\n    ^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 114, in process_images\n    result = app.run(image_path, detail_info)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 90, in run\n    modify_mask = utils.mask_change(src_mask, start_point, modify_detail.end_point, \"copying\")\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/processor/utils.py\", line 127, in mask_change\n    raise ValueError(\"目标区域超出编辑范围\")\nValueError: 目标区域超出编辑范围\n"
    },
    {
        "image_path": "/home/yuyangxin/data/dataset/MSCOCO/train2017/000000000030.jpg",
        "error_info": "Traceback (most recent call last):\n  File \"/home/yuyangxin/data/experiment/main.py\", line 142, in <module>\n    future.result()  # 获取结果\n    ^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/yuyangxin/anaconda3/envs/llama/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 114, in process_images\n    result = app.run(image_path, detail_info)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/main.py\", line 90, in run\n    modify_mask = utils.mask_change(src_mask, start_point, modify_detail.end_point, \"copying\")\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yuyangxin/data/experiment/processor/utils.py\", line 127, in mask_change\n    raise ValueError(\"目标区域超出编辑范围\")\nValueError: 目标区域超出编辑范围\n"
    }
]